on: [push]
jobs:
    Static-analysis:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: npm ci
            - run: npx tsc --noEmit
    Spellcheck:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: reviewdog/action-misspell@v1
              with:
                  github_token: ${{ secrets.github_token }}
